#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
    path: /register

login:
    path: /login
    defaults:
        _controller: App\Controller\SecurityController::login

login_check:
    path: /login_check

logout:
    path: /logout